In [14]:
# %%
#IMPORTACION DE LIBRERIAS
import pandas as pd
import datetime
import os
import numpy as np
import getpass

#hoy = datetime.datetime.today()
#hoy = datetime.date(2024, 10,14)
#LECTURA DE DFS
from pathlib import Path
usuario = getpass.getuser()

# %%


# %%
import tkinter as tk
from tkinter import ttk
from tkcalendar import DateEntry
import datetime

# Variable global para almacenar la fecha seleccionada


# Función que captura la fecha seleccionada y cierra la ventana
def seleccionar_y_continuar():
    global fecha_seleccionada
    
    # Obtener la fecha seleccionada como un objeto datetime.date
    fecha_input = calendario.get_date()

    # Convertir a datetime.date
    fecha_seleccionada = fecha_input
    
    # Cerrar la ventana
    ventana.destroy()

# Crear la ventana principal
ventana = tk.Tk()
ventana.title("Selección de Fecha")
ventana.geometry("300x250")

# Etiqueta de instrucción
label_instruccion = tk.Label(ventana, text="Selecciona una fecha:")
label_instruccion.pack(pady=10)

# Calendario de selección de fecha
calendario = DateEntry(ventana, date_pattern='dd.mm.yyyy', background='darkblue', foreground='white', borderwidth=2)
calendario.pack(pady=10)

# Botón para capturar la fecha y continuar
boton_ok = ttk.Button(ventana, text="OK", command=seleccionar_y_continuar)
boton_ok.pack(pady=10)

# Iniciar la aplicación
ventana.mainloop()

# Una vez que la ventana se cierra, la fecha ya está disponible como un objeto datetime.date
print(f"Fecha seleccionada: {fecha_seleccionada}")

# Aquí puedes continuar con el resto del código
# Ejemplo: 
# print(f"Usando la fecha seleccionada: {fecha_seleccionada}")



# %%
hoy = fecha_seleccionada


# %%

ruta = f'C:/Users/{usuario}/Inchcape/Planificación y Compras Chile - Documentos/Bases Indicadores en CSV {hoy.year}-{hoy.month:02d}'
ruta_repo = Path(ruta)

# %%
import pandas as pd

def excel_to_dataframe(xl_name: str, sh_name: str) -> pd.DataFrame:
    """
    Convert an Excel sheet to a pandas DataFrame.

    :param xl_name: The path to the Excel file.
    :param sh_name: The name of the sheet to be read.
    :return: A pandas DataFrame containing the data from the specified Excel sheet.
    """
    # Load the Excel file
    xls = pd.ExcelFile(xl_name)
    
    # Parse the specified sheet into a DataFrame
    df = xls.parse(sh_name)
    
    return df

# Example usage:



# %%
dtypes = {'Material actual':'str'}

# %%
ruta_sp = ruta_repo.joinpath('SP.csv')

df_sp = pd.read_csv(ruta_sp , dtype = dtypes, low_memory=False)

# %%
columnas= ['Nro_pieza_fabricante_1',	'Cod_Actual_1']
ruta_cod = ruta_repo.joinpath('COD_ACTUAL.csv')

# Leer el archivo CSV en un DataFrame
cadena_de_remplazo = pd.read_csv(ruta_cod)
cadena_de_remplazo = cadena_de_remplazo[columnas]


# %%
#MARA
columnas_mara = ['Material_R3','Part_number','Material_dsc','Modelo','Familia', 'Subfamilia', 'Categoría', 'Subcatgería','Sector_dsc']
ruta_mara = ruta_repo.joinpath('MARA_R3.csv')

# Leer el archivo CSV en un DataFrame
df_mara = pd.read_csv(ruta_mara, dtype={'Part_number':'str'})

print('Ruta Mara: ' + '\n' + str(ruta_mara))

# %%

#OBSOLECENCIA
#OBSOLECENCIA
columnas = ['ZFI_INNV1_T','ZFI_INNV2_T','ZFI_INNV3_T','ZFI_INNV4_T','ZFI_INNV5_T','ZFI_INNV6_T','ZFI_INNV7_T','sociedad_orig','Último Eslabón','Centro','obso_inchcape']

# for i in lista_maestro:
#     if 'new_obso' in i:
#         carpeta_obso = ruta_maestro + '/' + i
# df_obs_1 = excel_to_dataframe(carpeta_obso,'Base Obs Cierre Abr-24')

ruta_obs = ruta_repo.joinpath('OBSOLECENCIA.csv')

# Leer el archivo CSV en un DataFrame
df_obs_1 = pd.read_csv(ruta_obs)
df_obs_1 = df_obs_1[columnas]

Fecha seleccionada: 2026-02-25

C:\Users\lravlic\AppData\Local\Temp\ipykernel_24692\78174541.py:124: DtypeWarning: Columns (1,4,5,6,7,8,12,13,14,16,18,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df_mara = pd.read_csv(ruta_mara, dtype={'Part_number':'str'})

Ruta Mara:
C:\Users\lravlic\Inchcape\Planificación y Compras Chile - Documentos\Bases Indicadores en CSV 2026-02\MARA_R3.csv

In [15]:
ruta_lt = f"C:/Users/{usuario}/Inchcape/Planificación y Compras Chile - Documentos/Planificación y Compras KPI-Reportes/Disponibilidad Futura/2024/AXS/bases_python/LT Actuales Mar-24.xlsx"
df_lt = pd.read_excel(ruta_lt, header=1)


import tkinter as tk
from tkinter import filedialog

def seleccionar_archivo_tkinter(titulo):
    # Creamos una raíz temporal de Tkinter
    root = tk.Tk()
    
    # Esto es vital: ocultamos la ventanita gris vacía de Tkinter
    root.withdraw()
    
    # Forzamos a que el cuadro de diálogo aparezca al frente de todo
    root.attributes("-topmost", True)
    
    # Abrimos el selector de archivos
    archivo = filedialog.askopenfilename(
        title=titulo,
        filetypes=(("Archivos de Excel", "*.xlsx"), ("Todos los archivos", "*.*"))
    )
    
    # Cerramos la raíz de Tkinter inmediatamente después de elegir
    root.destroy()
    
    return archivo
dtypes = {'Almacén': 'str', 'Centro': 'str'}
print("Abriendo selector de archivos...")

# Usamos nuestra función segura para hilos
archivo_stock = seleccionar_archivo_tkinter("Selecciona el archivo de Stock")

if archivo_stock:
    print(f"Archivo de Stock seleccionado: {archivo_stock}")
    # Tu lógica de pandas aquí...
else:
    print("No se seleccionó ningún archivo.")

df_stock = pd.read_excel(archivo_stock, dtype=dtypes, sheet_name='Sheet1')





# Repite lo mismo para el archivo de TR
print("Abriendo selector de archivos...")

# Usamos nuestra función segura para hilos
archivo_tr = seleccionar_archivo_tkinter("Selecciona el archivo de TR FINAL R3 Consolidado")
if archivo_tr:
    print(f"Archivo de Stock seleccionado: {archivo_tr}")
    # Tu lógica de pandas aquí...
else:
    print("No se seleccionó ningún archivo.")
df_tr = pd.read_excel(archivo_tr, sheet_name='Sheet1')
# Repite lo mismo para el archivo de TR


# #STOCK
# ruta_tubo = f"C:/Users/{usuario}/Inchcape/Planificación y Compras Chile - Documentos/Planificación y Compras KPI-Reportes/Tubo Semanal"
# carpetas_tubo = os.listdir(ruta_tubo)
# tubo = carpetas_tubo[-2]
# ubi_tubo = ruta_tubo + '/' + tubo + '/' + tubo
# archivo_tr = ruta_tubo + '/' + tubo + '/' + tubo + ' - TR FINAL R3 Consolidado.xlsx'
# archivo_tubo = ruta_tubo + '/' + tubo + '/' + tubo + ' - Stock R3.xlsx'
# print(tubo)
# dtypes = {'Almacén':'str', 'Centro':'str'}
# # dtypes = {'Almacén':'str'}
# df_stock = pd.read_excel(archivo_tubo, dtype = dtypes,sheet_name = 'Sheet1')


# # #TRANSITO
# df_tr = pd.read_excel(archivo_tr,sheet_name = 'Sheet1')

# %%
#Reseteo de OBS
df_sp_1 = df_sp
df_obs = df_obs_1

# %%
df_obs_1 = df_obs_1.rename(columns={'Último Eslabón': 'Ultimo Eslabon'}, inplace = True)

Abriendo selector de archivos...
Archivo de Stock seleccionado: C:/Users/lravlic/Inchcape/Planificación y Compras Chile - Documentos/Planificación y Compras KPI-Reportes/Tubo Semanal/2026-02-23/2026-02-23 - Stock R3.xlsx
Abriendo selector de archivos...
Archivo de Stock seleccionado: C:/Users/lravlic/Inchcape/Planificación y Compras Chile - Documentos/Planificación y Compras KPI-Reportes/Tubo Semanal/2026-02-23/2026-02-23 - TR FINAL R3 Consolidado.xlsx

TypeError: DataFrame.merge() got an unexpected keyword argument 'dtypes'

In [17]:
# %%
df_sp_1 = df_sp_1.merge(cadena_de_remplazo, left_on='Material actual', right_on='Nro_pieza_fabricante_1', how='left')
df_sp_1['Cod_Actual_1'] = df_sp_1['Cod_Actual_1'].fillna(df_sp_1['Material actual'])
df_sp_1 = df_sp_1.drop('Nro_pieza_fabricante_1', axis=1)

In [20]:
df_sp_1['Vigencia Derco'] = df_sp_1['Vigencia Derco'].astype('str')

In [23]:
# filtra todos los registros cuya cadena de `Vigencia Derco`
# contiene el carácter "1"
df_codigo = df_sp_1[
    df_sp_1['Vigencia Derco'].astype(str).str.contains('1', na=False)
]

In [24]:
df_codigo

,Material actual,UE,Descripción,Sector,Familia,Subfamilia,Categoría,Subcategoría,Factor,Cod. Proveedor,...,Verificación,Input PM .1,Verificación.1,marca,modelo,proveedor,costo según maestra,dif,UE Febrero,Cod_Actual_1
30,BARTRACX30TOEM,BARTRACX30TOEM,AXS. BARRA TRANSVERSAL CX-30 TOEM BK,Accesorios,NaN,NaN,NaN,NaN,1.0,40003818,...,1.0,0.0,1.0,MAZDA,CX-30,Ningbo Chenfan Auto Accessories Co.,62858.424999999996,0.000000,BARTRACX30TOEM,BARTRACX30TOEM
34,503399,503399,AXS. LONA MARITIMA MZD NEW BT-50 IS ZR,Accesorios,ACCESORIOS Y HERRAMIENTAS,ACCESORIOS EXTERIORES,ESTETICA,TAPAS Y LONAS PARA PICK UP,1.0,40003304,...,1.0,0.0,1.0,MAZDA,BT-50,CHANGZHOU SUNWOOD INTERNATIONAL TRA,98565,0.000000,503399,503399
41,37005,37005,AXS. TARJETA MICRO SD 64GB KINGSTON,Accesorios,NaN,NaN,NaN,NaN,1.0,10194607,...,1.0,40.0,1.0,UNIVERSAL,UNIVERSAL,AUDIO MATICS SPA,5271.678571428572,7.678571,37005,37005
44,2080V2PSE105CES,2080V2PSE105CES,AXS. EMOV CARGADOR DE VIAJE T2,Accesorios,NaN,NaN,NaN,NaN,1.0,40003900,...,1.0,131.0,1.0,UNIVERSAL,UNIVERSAL,Zhangjiagang Uchen New Energy Techn,99275.00000000001,0.000000,2080V2PSE105CES,2080V2PSE105CES
46,BARLONCX30TOEM,BARLONCX30TOEM,AXS. BARRA LONGITUDINAL CX-30 TOEM BK,Accesorios,NaN,NaN,NaN,NaN,1.0,40003818,...,1.0,0.0,1.0,MAZDA,CX-30,Ningbo Chenfan Auto Accessories Co.,62869.579999999994,0.000000,BARLONCX30TOEM,BARLONCX30TOEM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9285,81BARRACX60E,81BARRACX60E,AXS. BARRAS CX-60 THULE EDGE,Accesorios,NaN,NaN,NaN,NaN,1.0,10016290,...,1.0,0.0,1.0,MAZDA,CX-60,Emasa Chile Spa,405858,405858.000000,81BARRACX60E,81BARRACX60E
9372,TRIMBIKE,TRIMBIKE,AXS. PORTABICICLETA PAD PICKUP,Accesorios,NaN,NaN,NaN,NaN,1.0,10025423,...,1.0,0.0,1.0,UNIVERSAL,UNIVERSAL,THERMOFORM SAS,No disponible,NaN,TRIMBIKE,TRIMBIKE
9389,GJFJ00306PTK3,GJFJ00306PTK3,AXS. PLATAFORMA DE TECHO GWM TANK 300,Accesorios,NaN,NaN,NaN,NaN,1.0,40000176,...,1.0,0.0,1.0,GWM,TANK 300,GREAT WALL MOTOR COMPANY LIMITED,410732,410732.000000,GJFJ00306PTK3,GJFJ00306PTK3
9426,GJFJ00325P,GJFJ00325P,AXS. TAPA RETRACTIL ELECTRICA GWM POER,Accesorios,NaN,NaN,NaN,NaN,1.0,40000176,...,1.0,0.0,1.0,GWM,POER,GREAT WALL MOTOR COMPANY LIMITED,681968,681968.000000,GJFJ00325P,GJFJ00325P
9449,GJFJ00189P,GJFJ00189P,AXS. TAPA RETRACTIL POER P500 PREMIUM,Accesorios,NaN,NaN,NaN,NaN,1.0,40000176,...,1.0,0.0,1.0,GWM,POER 500,GREAT WALL MOTOR COMPANY LIMITED,733280.5,733280.500000,GJFJ00189P,GJFJ00189P

In [25]:


# %%
df_codigo = df_sp_1[
    df_sp_1['Vigencia Derco'].astype(str).str.contains('1', na=False)
]

# %%
df_codigo.drop_duplicates(subset='Material actual', inplace=True)

# %%
df_mara.drop_duplicates(subset='Material_R3', inplace=True)

# %%


# %%
df_codigo = df_codigo[['Material actual','Cod_Actual_1','Descripción','Cod. Proveedor','Proveedor','Plan Híbrido 2 UN v2','Origen','CES','PDI','Nuevo','Lead Time']]

# %%
df_base = pd.merge(df_codigo, df_mara, left_on = 'Cod_Actual_1', right_on='Material_R3', how='left')
df_base['Part_number'] = df_base['Part_number'].str.replace(r'\[\#\]', '', regex=True)




anio = hoy.year if hoy.month > 1 else hoy.year - 1
mes = hoy.month - 1 if hoy.month > 1 else 12

# Formatear mes como dos dígitos
mes_formateado = str(mes).zfill(2)

# Ruta base
# Cambia esto al nombre del usuario correspondiente
ruta_fc = f"C:/Users/{usuario}/Inchcape/Planificación y Compras Chile - Documentos/Planificación y Compras OEM/Demanda y New Model Parts/Demanda/Demanda Mainstream/Forecast Colaborado/{anio}"

# Listar carpetas en la ruta base
try:
    lista_fc = os.listdir(ruta_fc)
    for i in lista_fc:
        if str(anio) in i and mes_formateado in i:
            archivos_fc = os.listdir(f"{ruta_fc}/{i}")
            for j in archivos_fc:
                print(j)
                if 'AXS' in j:
                    archivo = f"{ruta_fc}/{i}/{j}"
                    df_fc = pd.read_excel(archivo, sheet_name='MOS Forecast Data', header=3)
except FileNotFoundError:
    print(f"La ruta {ruta_fc} no existe. Verifica el nombre del usuario o la e")
df_fc_final = ['Último Eslabón']
for item in df_fc.columns.to_list():
    if "FC" in item:
        df_fc_final.append(item)
df_fc_final = df_fc_final[:13]
df_fc_prom = df_fc[df_fc_final]

df_fc_prom = df_fc_prom.merge(cadena_de_remplazo, left_on='Último Eslabón', right_on='Nro_pieza_fabricante_1', how ='left')
df_fc_prom['Cod_Actual_1'] = df_fc_prom['Cod_Actual_1'].fillna(df_fc_prom['Último Eslabón'])

df_fc_prom.drop(columns=['Último Eslabón','Nro_pieza_fabricante_1'], inplace=True)
columnas_prom = [col for col in df_fc_prom.columns if 'Suma' in col]
df_fc_prom
df_fc_prom.columns = [col.replace('Suma de', 'FC') for col in df_fc_prom.columns]
df_fc_prom.columns = [col.replace('sept', 'sep')  for col in df_fc_prom.columns]
# columnas_seleccionadas = ['Cod_Actual_1'] + [col for col in df_fc_prom.columns if 'FC' in col and 'Prom' not in col][:10]

# nuevo_df_fc_prom = df_fc_prom[columnas_seleccionadas].copy()
df_fc_prom = df_fc_prom.groupby('Cod_Actual_1').sum()
df_fc_prom = df_fc_prom.reset_index()

df_fc_prom.columns = [col[:-1] if col.startswith('FC') else col for col in df_fc_prom.columns]


df_fc_prom.columns

# %%
# Filter columns that start with 'FC'
columns_to_process = [col for col in df_fc_prom.columns if col.startswith('FC')]
df_fc_prom
columns_to_process
df_fc_prom[columns_to_process[0]]
df_fc_prom[columns_to_process[1:7]]

df_fc_prom['Promedio FC'] = df_fc_prom[columns_to_process[1:7]].mean(axis=1)
df_fc_prom['Promedio FC Piso'] = df_fc_prom[columns_to_process[0:3]].mean(axis=1)

#Multiply the first column by 0.33 and add the result to each of the next three columns
multiplied_column = df_fc_prom[columns_to_process[0]] * 0.333
for col in columns_to_process[1:4]:
    df_fc_prom[col] = df_fc_prom[col] + multiplied_column
    #print(col)



for col in columns_to_process:
    df_fc_prom[col] = df_fc_prom[col]/4.33






#Drop the first column
df_fc_prom['Stock de piso'] = df_fc_prom[columns_to_process[0]] 
df_fc_prom.drop(columns_to_process[0], axis=1, inplace=True)

# %%


# %%
df_fc_final_venta = ['Último Eslabón']
for item in [col for col in df_fc.columns if 'Vta R' in col and not 'Vigencia' in col][:6]:
    print(item)
    df_fc_final_venta.append(item)


# %%
df_fc_final_venta

# %%
df_fc_prom_venta = df_fc[df_fc_final_venta]

# %%
df_fc_prom_venta = df_fc_prom_venta.merge(cadena_de_remplazo, left_on='Último Eslabón', right_on='Nro_pieza_fabricante_1', how ='left')
df_fc_prom_venta['Cod_Actual_1'] = df_fc_prom_venta['Cod_Actual_1'].fillna(df_fc_prom_venta['Último Eslabón'])
df_fc_prom_venta.drop(columns=['Último Eslabón','Nro_pieza_fabricante_1'], inplace=True)
columnas_prom_venta = [col for col in df_fc_prom_venta.columns if 'Vta R' in col][:6]
df_fc_prom_venta['Promedio Venta'] = df_fc_prom_venta[columnas_prom_venta].mean(axis=1)
# columnas_seleccionadas = ['Cod_Actual_1'] + [col for col in df_fc_prom.columns if 'FC' in col and 'Prom' not in col][:10]
# nuevo_df_fc_prom = df_fc_prom[columnas_seleccionadas].copy()


df_fc_prom_venta = df_fc_prom_venta[['Cod_Actual_1', 'Promedio Venta']]
df_fc_prom_venta = df_fc_prom_venta.groupby(['Cod_Actual_1'])['Promedio Venta'].sum().reset_index()

# %%
df_stock['Total'] = df_stock['Libre utilización'] + df_stock['Trans./Trasl.'] + df_stock['En control calidad']

# Eliminar las columnas no necesarias
columns_to_drop = ['Libre utilización', 'Trans./Trasl.', 'En control calidad']
df_stock = df_stock.drop(columns=columns_to_drop)

# Filtrar las filas que cumplen con las condiciones especificadas
condicion = (
    ((df_stock['Centro'] == '201') & (df_stock['Almacén'] == '1100'))
)

condicion_2 = (
    ((df_stock['Almacén'] == '1500') | (df_stock['Almacén'] == '1505')))


df_stock_cd = df_stock[condicion]
df_stock_pañol = df_stock[condicion_2]

# Agrupar por 'Ult. Eslabon' y sumar la columna 'Total'
df_stock_cd = df_stock_cd.groupby(['Ult. Eslabon']).agg({'Total': 'sum'}).reset_index()
df_stock_pañol = df_stock_pañol.groupby(['Ult. Eslabon']).agg({'Total': 'sum'}).reset_index()

# %%
df_base = df_base.merge(df_stock_cd, left_on='Cod_Actual_1', right_on='Ult. Eslabon', how='left')
df_base = df_base.merge(df_stock_pañol, left_on='Cod_Actual_1', right_on='Ult. Eslabon', how='left')


# %%
columnas = {'Total_x':'Stock CD','Total_y':'Stock Pañol'}
columnas_drop = ['Ult. Eslabon_x','Ult. Eslabon_y']
df_base.rename(columns=columnas, inplace=True)
df_base.drop(columns = columnas_drop, inplace=True)


# %%
df_fc_prom

# %%
df_base = df_base.merge(df_fc_prom, left_on='Cod_Actual_1', right_on = 'Cod_Actual_1', how='left')
df_base = df_base.merge(df_fc_prom_venta, left_on='Cod_Actual_1', right_on = 'Cod_Actual_1', how='left')

# %%
def custom_formula(row):
    AH = row['Stock CD']
    T = row['Promedio FC']
    if AH == 0:
        return 0 if T == 0 else (AH / T)
    else:
        return AH / T if T != 0 else 12

# Apply the custom function to the DataFrame
df_base['Cobertura Stock'] = df_base.apply(custom_formula, axis=1)

# %%
df_base['Cobertura Stock'].sum()

# %%
df_sp_costo_1 = df_sp_1[['Material actual','Costo Un']]
df_sp_costo_1.drop_duplicates(subset=['Material actual'], inplace=True)
df_base = df_base.merge(df_sp_costo_1[['Material actual','Costo Un']], left_on='Material actual', right_on='Material actual', how= 'left')
df_sp_costo = df_sp_1[['Cod_Actual_1','Costo Un']].sort_values(by='Costo Un', ascending=False)
df_sp_costo.drop_duplicates(subset=['Cod_Actual_1'], keep='first', inplace=True)
df_base = df_base.merge(df_sp_costo, left_on='Cod_Actual_1', right_on='Cod_Actual_1', how='left')
df_base['Costo Un_x'] = df_base['Costo Un_x'].fillna(df_base['Costo Un_y'])
df_base.drop(['Costo Un_y'], inplace = True, axis=1)
df_base = df_base.rename(columns = {'Costo Un_x':'Costo CPP'})


# %%
df_sp_moq_1 = df_sp_1[['Material actual','Cod_Actual_1','MOQ']]
df_sp_moq_1.drop_duplicates(subset=['Material actual'],keep='first', inplace=True)
df_base = df_base.merge(df_sp_moq_1[['Material actual','MOQ']], left_on='Material actual', right_on='Material actual', how= 'left')
df_sp_moq = df_sp_1[['Cod_Actual_1','MOQ']].sort_values(by='MOQ',ascending=False)
df_sp_moq.drop_duplicates(subset=['Cod_Actual_1'], keep='first', inplace=True)
df_base = df_base.merge(df_sp_moq, left_on='Cod_Actual_1', right_on='Cod_Actual_1', how='left')
df_base['MOQ_x'] = df_base['MOQ_x'].fillna(df_base['MOQ_y'])

df_base = df_base.rename(columns = {'MOQ_x':'MOQ'})
df_base.drop(columns='MOQ_y', inplace=True)

C:\Users\lravlic\AppData\Local\Temp\ipykernel_24692\2423872174.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_codigo.drop_duplicates(subset='Material actual', inplace=True)

01.2026 S&OP ForecastColaboradoAXS_CES&PDI_CicloEne (WH).xlsx
01.2026 S&OP ForecastColaboradoAXS_CES&PDI_CicloEne2026.xlsx
01.2026 S&OP ForecastColaboradoOEM_Mainstream_CicloFeb2026 v2.xlsm
01.2026 S&OP ForecastColaboradoOEM_Mainstream_CicloFeb2026.xlsx
Vta R de ene-25
Vta R de feb-25
Vta R de mar-25
Vta R de abr-25
Vta R de may-25
Vta R de jun-25

C:\Users\lravlic\AppData\Local\Temp\ipykernel_24692\2423872174.py:193: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sp_costo_1.drop_duplicates(subset=['Material actual'], inplace=True)
C:\Users\lravlic\AppData\Local\Temp\ipykernel_24692\2423872174.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sp_moq_1.drop_duplicates(subset=['Material actual'],keep='first', inplace=True)

In [26]:
df_base

,Material actual,Cod_Actual_1,Descripción,Cod. Proveedor,Proveedor,Plan Híbrido 2 UN v2,Origen,CES,PDI,Nuevo,...,FC oct-26,FC nov-26,FC dic-26,Promedio FC,Promedio FC Piso,Stock de piso,Promedio Venta,Cobertura Stock,Costo CPP,MOQ
0,BARTRACX30TOEM,BARTRACX30TOEM,AXS. BARRA TRANSVERSAL CX-30 TOEM BK,40003818,NINGBO CHENFAN AUTO ACCES,0,IMP,1,0,0,...,0.000000,0.000000,0.000000,23.333333,26.666667,4.618938,0.000000,4.328571,62858.425,100.0
1,503399,503399,AXS. LONA MARITIMA MZD NEW BT-50 IS ZR,40003304,CHANGZHOU SUNWOOD INTERNA,0,IMP,1,0,0,...,4.618938,4.618938,4.618938,15.000000,13.333333,2.309469,4.500000,0.666667,98565.000,100.0
2,37005,37005,AXS. TARJETA MICRO SD 64GB KINGSTON,10194607,AUDIO MATICS SPA,40,NAC,0,1,0,...,7.390300,7.621247,7.621247,27.000000,28.000000,8.083141,59.333333,2.037037,5264.000,1.0
3,2080V2PSE105CES,2080V2PSE105CES,AXS. EMOV CARGADOR DE VIAJE T2,40003900,ZHANGJIAGANG UCHEN NEW EN,131,IMP,1,1,0,...,72.517321,72.979215,80.369515,268.500000,291.666667,82.909931,0.000000,NaN,99275.000,1.0
4,BARLONCX30TOEM,BARLONCX30TOEM,AXS. BARRA LONGITUDINAL CX-30 TOEM BK,40003818,NINGBO CHENFAN AUTO ACCES,0,IMP,1,0,0,...,0.000000,0.000000,0.000000,23.333333,26.666667,4.618938,0.000000,4.285714,62869.580,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,81BARRACX60E,81BARRACX60E,AXS. BARRAS CX-60 THULE EDGE,10016290,EMASA CHILE SPA,0,NAC,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,0.000,1.0
272,TRIMBIKE,TRIMBIKE,AXS. PORTABICICLETA PAD PICKUP,10025423,THERMOFORM SAS,0,IMP,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
273,GJFJ00306PTK3,GJFJ00306PTK3,AXS. PLATAFORMA DE TECHO GWM TANK 300,40000176,GREAT WALL MOTOR COMPANY,0,IMP,0,0,1,...,0.000000,0.000000,0.000000,0.666667,1.000000,0.230947,0.000000,1.500000,0.000,1.0
274,GJFJ00325P,GJFJ00325P,AXS. TAPA RETRACTIL ELECTRICA GWM POER,40000176,GREAT WALL MOTOR COMPANY,0,IMP,0,0,1,...,0.000000,0.000000,0.000000,0.500000,0.333333,0.000000,0.000000,2.000000,0.000,1.0
275,GJFJ00189P,GJFJ00189P,AXS. TAPA RETRACTIL POER P500 PREMIUM,40000176,GREAT WALL MOTOR COMPANY,0,IMP,1,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,0.000,1.0

In [9]:
df_codigo

Empty DataFrame
Columns: [Material actual, Cod_Actual_1, Descripción, Cod. Proveedor, Proveedor, Plan Híbrido 2 UN v2, Origen, CES, PDI, Nuevo, Lead Time]
Index: []